blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
# import debug_toolbar
app_name="blog"
urlpatterns = [
    # path('', views.index, name='index'),
    
    path('', views.IndexView.as_view(), name='index'),

    path('archives/', views.ArchivesView.as_view(),name='archives'),
    path('post/<int:pk>', views.article, name='article'),
    #path('post/', views.myview, name='myview'),

    path('category/<int:pk>', views.CategoryView.as_view(), name='category'),
    path('categories/', views.Categories.as_view(), name='categories'),

    path('tags/', views.TagsView.as_view(),name='tags'),
    path('tag_list/<int:pk>', views.TagListView.as_view(), name='tag_list'),

    path('books/', views.BooksView.as_view(), name='books'),
    path('book_detail/<int:pk>', views.book_detail, name='book_detail'),
    path('book_list/<int:pk>', views.BookListView.as_view(), name='book_list'),

    path('movies/', views.MoviesView.as_view(), name ='movies' ),
    path('movie_detail/<int:pk>', views.movie_detail, name='movie_detail'),
    path('movie_list/<int:pk>', views.MovieListView.as_view(), name='movie_list'),

    path('login/',views.login,name='login'),
    path('register/',views.register,name='register'),

    path('messages/',views.messages,name='messages'),

    path('courses/',views.CoursesView.as_view(),name='courses'),
    path('course/<int:pk>',views.course,name='course'),

]

comment/urls.py
from django.urls import path
from . import views

app_name="comment"

urlpatterns = [
    path('update_comment', views.update_comment, name ='update_comment'),
]

djangoblog/urls.py
import xadmin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include

from werobot.contrib.django import make_view
from robot import robot

urlpatterns = [
    path('admin/', xadmin.site.urls,name="admin"),
    path('', include('blog.urls')),
    path('search/', include('haystack.urls')),
    path('mdeditor/', include('mdeditor.urls')),
    path('comment/', include('comment.urls')),
    path('robot/',make_view(robot)),

]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # import debug_toolbar
    # urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

blog/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.html import strip_tags
import django.utils.timezone as timezone
from mdeditor.fields import MDTextField
# 创建博文分类的表
class Category(models.Model):
	name = models.CharField(max_length=100,verbose_name='分类名称')

	def __str__(self):
		return self.name
	class Meta:
		verbose_name="分类目录"
		verbose_name_plural = verbose_name
	def get_absolute_url(self):
		return reverse('blog:category', kwargs={'pk': self.pk})



# 创建文章标签的表
class Tag(models.Model):
	# name是标签名的字段
	name = models.CharField(max_length=100,verbose_name='标签名称')
	def __str__(self):
		return self.name

	class Meta:
		verbose_name="标签列表"
		verbose_name_plural = verbose_name

	def get_absolute_url(self):
		return reverse('blog:tag_list', kwargs={'pk': self.pk})


# 创建文章的类
class Post(models.Model):

	title = models.CharField(max_length=1000,verbose_name='标题')
	body = MDTextField(verbose_name='正文')
	created_time = models.DateTimeField(null=True,verbose_name='创建时间',default = timezone.now)
	modified_time = models.DateTimeField(verbose_name='修改时间',auto_now = True)
	excerpt = models.CharField(max_length=300,blank=True,verbose_name='摘要')
	views = models.PositiveIntegerField(default=0)
	words = models.PositiveIntegerField(default=0)
	category = models.ForeignKey(Category,verbose_name='文章分类',on_delete=models.CASCADE)
	tag = models.ManyToManyField(Tag,verbose_name='标签类型')
	author = models.ForeignKey(User,verbose_name='作者',on_delete=models.CASCADE,default="reborn")

	def get_absolute_url(self):
		return reverse('blog:article', kwargs={'pk': self.pk})

	def __str__(self):
		return self.title

	# 阅读量增加1
	def increase_views(self):
		self.views += 1
		self.save(update_fields=['views'])

	def save(self, *args, **kwargs):
		if not self.excerpt:
			self.excerpt = strip_tags(self.body).replace("&nbsp;","").replace("#","")[:150] #strip_tags是去除html标签
		self.words = len(strip_tags(self.body).replace(" ","").replace('\n',""))	# 统计文章字数
		super(Post, self).save(*args, **kwargs) # 调用父类的 save 方法将数据保存到数据库中

	class Meta:
		verbose_name="文章列表"
		verbose_name_plural = verbose_name
		ordering= ['-pk']

class BookCategory(models.Model):
	name = models.CharField(max_length=100,verbose_name="分类名称")

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = "图书分类"
		verbose_name_plural = verbose_name

class BookTag(models.Model):
	name = models.CharField(max_length=100,verbose_name="标签")

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('blog:book_list', kwargs={'pk': self.pk})

	class Meta:
		verbose_name = "书籍标签"
		verbose_name_plural = verbose_name


class Book(models.Model):
	name = models.CharField(max_length=100,verbose_name="书名")
	author = models.CharField(max_length=100, verbose_name="作者")
	category = models.ForeignKey(BookCategory,on_delete=models.CASCADE,verbose_name="书籍分类")
	tag = models.ManyToManyField(BookTag,verbose_name="本书标签")
	cover = models.ImageField(upload_to='books',verbose_name="封面图",blank=True)
	score = models.DecimalField(max_digits=2,decimal_places=1,verbose_name="豆瓣评分")
	title = models.CharField(max_length=100, verbose_name="标题",blank=True)
	detail = MDTextField(verbose_name="读书笔记", null=True,blank=True)
	created_time = models.DateField(null=True,default = timezone.now,verbose_name="添加时间")
	time_consuming = models.CharField(max_length=100,verbose_name="阅读初始时间")
	views = models.PositiveIntegerField(default=0,verbose_name="阅读量")
	words = models.PositiveIntegerField(default=0,verbose_name="字数")
	excerpt = models.CharField(max_length=300, blank=True, verbose_name='摘要')


	def get_absolute_url(self):
		return reverse('blog:book_detail', kwargs={'pk': self.pk})

	def __str__(self):
		return self.name

	# 阅读量增加1
	def increase_views(self):
		self.views += 1
		self.save(update_fields=['views'])

	def save(self, *args, **kwargs):
		if not self.excerpt:
			self.excerpt = strip_tags(self.detail).replace("&nbsp;","").replace("#","")[:150] #strip_tags是去除html标签
		self.words = len(strip_tags(self.detail).replace(" ","").replace('\n',""))	# 统计文章字数
		super(Book, self).save(*args, **kwargs) # 调用父类的 save 方法将数据保存到数据库中

	class Meta:
		verbose_name="我的书单"
		verbose_name_plural = verbose_name


class MovieCategory(models.Model):
	name = models.CharField(max_length=100,verbose_name="电影分类")

	def __str__(self):
		return self.name

	class Meta:
		verbose_name="电影分类"
		verbose_name_plural = verbose_name

class MovieTag(models.Model):
	name = models.CharField(max_length=100,verbose_name="标签名称",blank=True)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('blog:movie_list',kwargs={'pk':self.pk})

	class Meta:
		verbose_name="电影标签"
		verbose_name_plural=verbose_name

class Movie(models.Model):
	name = models.CharField(max_length=100,verbose_name="电影名称")
	director = models.CharField(max_length=100,verbose_name="导演")
	actor = models.CharField(max_length=100,verbose_name="主演")
	category = models.ForeignKey(MovieCategory,on_delete=models.CASCADE,verbose_name="电影分类",)
	tag = models.ManyToManyField(MovieTag,verbose_name="电影标签")
	cover = models.ImageField(upload_to='movies',verbose_name="上传封面",blank=True)
	score = models.DecimalField(max_digits=2,decimal_places=1,verbose_name="豆瓣评分")
	release_time = models.DateField(verbose_name="上映时间")
	created_time = models.DateField(default=timezone.now,verbose_name="添加时间")
	length_time = models.PositiveIntegerField(default=0,verbose_name="电影时长")
	watch_time = models.DateField(default=timezone.now,verbose_name="观看时间")
	title = models.CharField(max_length=100,verbose_name="标题",blank=True)
	detail = MDTextField(blank=True,null=True,verbose_name="观影后感")
	views = models.PositiveIntegerField(default=0, verbose_name="阅读量")
	words = models.PositiveIntegerField(default=0, verbose_name="字数")
	excerpt = models.CharField(max_length=300, blank=True, verbose_name='摘要')

	def __str__(self):
		return self.name

	# 阅读量增加1
	def increase_views(self):
		self.views += 1
		self.save(update_fields=['views'])

	def save(self, *args, **kwargs):
		if not self.excerpt:
			self.excerpt = strip_tags(self.detail).replace("&nbsp;","").replace("#","")[:150] #strip_tags是去除html标签
		self.words = len(strip_tags(self.detail).replace(" ","").replace('\n',""))	# 统计文章字数
		super(Movie, self).save(*args, **kwargs) # 调用父类的 save 方法将数据保存到数据库中

	def get_absolute_url(self):
		return reverse('blog:movie_detail', kwargs={'pk': self.pk})

	class Meta:
		verbose_name="我的影单"
		verbose_name_plural = verbose_name

class Messages(models.Model):
	name = models.CharField(max_length=100,verbose_name="给我留言")
	class Meta:
		verbose_name = "网站留言"
		verbose_name_plural = verbose_name

class MeanList(models.Model):
	title = models.CharField(max_length=100,verbose_name="菜单名称")
	link = models.CharField(max_length=100,verbose_name="菜单链接",blank=True,null=True,)
	icon = models.CharField(max_length=100,verbose_name="菜单图标",blank=True,null=True,)

	class Meta:
		verbose_name = "菜单栏"
		verbose_name_plural = verbose_name



class Courses(models.Model):
	title = models.CharField(max_length=100,verbose_name="教程名称")
	cover = models.ImageField(upload_to='course',verbose_name="上传封面",blank=True)
	views = models.PositiveIntegerField(default=0, verbose_name="阅读量")
	category = models.CharField(max_length=100,verbose_name="教程分类")
	introduce = models.CharField(max_length=200,verbose_name="教程简介",blank=True)
	status = models.CharField(max_length=50,verbose_name="更新状态")
	created_time = models.DateTimeField(null=True, verbose_name='创建时间', default=timezone.now)
	author = models.ForeignKey(User, verbose_name='作者', on_delete=models.DO_NOTHING, default="reborn")
	comments = models.PositiveIntegerField(default=0, verbose_name="评论数")
	numbers = models.PositiveIntegerField(default=0, verbose_name="教程数量")

	class Meta:
		verbose_name = "教程列表"
		verbose_name_plural = verbose_name

	def get_absolute_url(self):
		return reverse('blog:course', kwargs={'pk': self.pk})

blog/views.py
import markdown
from .models import *
from django.contrib import auth
from django.db.models import Count
from django.views.generic import ListView
from django.contrib.auth.models import User
from djangoblog.form import LoginForm,RegForm
from django.shortcuts import render,get_object_or_404,redirect


class IndexView(ListView):
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    paginate_by = 7

    def get_queryset(self):
        return Post.objects.all()

def myview(request):
    context = {}
    return render(request, 'blog/article.html', context)

def article(request, pk):
    post = get_object_or_404(Post, pk=pk)
    author = User.objects.get(id=post.author_id)
    category = Category.objects.get(id=post.category_id)
    post.increase_views() # 阅读量加1
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])
    post.body = md.convert(post.body)
    post.toc = md.toc
    # 获取相关文章
    relative_posts = Post.objects.filter(category_id=post.category_id).exclude(pk = pk).order_by('?')[:4]

    context = {}
    context['post'] = post
    context['author'] = author
    context['category'] = category
    context['relative_posts'] = relative_posts
    return render(request, 'blog/article.html', context)

class ArchivesView(ListView):
    template_name = 'blog/archives.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.all().order_by('-created_time')

#全站所有的标签
class TagsView(ListView):
    model = Tag
    template_name = 'blog/tags.html'
    context_object_name = 'tags'

#每个标签下的所有文章
class TagListView(ListView):
    template_name = 'blog/tag_list.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        tag = get_object_or_404(Tag,pk = self.kwargs.get('pk'))
        return Post.objects.filter(tag=tag).order_by('-created_time')

    def get_context_data(self, **kwargs):
        context = super(TagListView, self).get_context_data(**kwargs)
        context['tag_name'] = Tag.objects.get(pk = self.kwargs.get('pk'))
        return context

class CategoryView(ListView):
    template_name = 'blog/category.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return Post.objects.filter(category=cate).order_by('-created_time')

    def get_context_data(self, **kwargs):
        context = super(CategoryView, self).get_context_data(**kwargs)
        context['cate_name'] = Category.objects.get(pk=self.kwargs.get('pk'))
        return context

# 按分类展示文章
class Categories(ListView):
    model = Post
    template_name = 'blog/categories.html'
    context_object_name = 'posts'

class BooksView(ListView):
    template_name = 'blog/books.html'
    context_object_name = 'books'
    paginate_by = 9

    def get_queryset(self):
        return Book.objects.all().order_by('-pk')

class BookListView(ListView):
    template_name = 'blog/book_list.html'
    context_object_name = 'books'
    paginate_by = 9

    def get_queryset(self):
        tag = get_object_or_404(BookTag,pk = self.kwargs.get('pk'))
        return Book.objects.filter(tag=tag).order_by('-created_time')

    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        context['tag_name'] = BookTag.objects.get(pk = self.kwargs.get('pk'))
        return context

def book_detail(request,pk):
    book = get_object_or_404(Book,pk=pk)
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])
    book.detail = md.convert(book.detail)
    book.toc = md.toc
    book.increase_views()  # 阅读量加1
    tags = BookTag.objects.annotate(posts_count = Count('book')).order_by('-posts_count')
    return render(request,'blog/book_detail.html',{'book':book,'tags':tags,})

class MoviesView(ListView):
    template_name = 'blog/movies.html'
    context_object_name = 'movies'
    paginate_by = 9

    def get_queryset(self):
        return Movie.objects.all().order_by('-created_time')

class MovieListView(ListView):
    template_name = 'blog/movies_list.html'
    context_object_name = 'movies'
    paginate_by = 9

    def get_queryset(self):
        tag = get_object_or_404(MovieTag,pk = self.kwargs.get('pk'))
        return Movie.objects.filter(tag=tag).order_by('-created_time')

    def get_context_data(self, **kwargs):
        context = super(MovieListView, self).get_context_data(**kwargs)
        context['tag_name'] = MovieTag.objects.get(pk = self.kwargs.get('pk'))
        return context

def movie_detail(request,pk):
    movie = get_object_or_404(Movie,pk=pk)
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])
    movie.detail = md.convert(movie.detail)
    movie.toc = md.toc
    movie.increase_views()  # 阅读量加1

    tags = MovieTag.objects.annotate(movies_count = Count('movie')).order_by('-movies_count')
    return render(request,'blog/movie_detail.html',{'movie':movie,'tags':tags,})


# 显示登录页面、进行登录操作
def login(request):
    # 此处只有登录的操作，验证的部分在forms.py完成
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user = login_form.cleaned_data['user']
            auth.login(request, user)
            return redirect(request.GET.get('from',reverse('blog:index'))) # 重定向到上一个页面
    else:
        login_form = LoginForm()
    context = {}
    context['login_form'] = login_form
    return render(request, 'blog/login.html', context)


# 显示注册页面、进行注册操作
def register(request):
    if request.method == 'POST':
        reg_form = RegForm(request.POST)
        if reg_form.is_valid():
            username = reg_form.cleaned_data['username']
            password = reg_form.cleaned_data['password']
            email = reg_form.cleaned_data['email']

            # 注册用户
            user = User()
            user.username = username
            user.email = email
            user.set_password(password)
            user.save()

            # 注册后自动登录
            user = auth.authenticate(username=username,password=password)
            auth.login(request,user)

            # 跳转到进入注册页面之前的页面
            return redirect(request.GET.get('from',reverse('blog:index')))  # 重定向到上一个页面

    else:
        reg_form = RegForm()
    context = {}
    context['reg_form'] = reg_form
    return render(request,'blog/register.html',context)

def messages(request):
    messages = Messages.objects.get(pk=1)
    return render(request,'blog/messages.html',{'messages':messages})


class CoursesView(ListView):
    template_name = 'blog/courses.html'
    context_object_name = 'courses'

    def get_queryset(self):
        return Courses.objects.all().order_by('-created_time')

def course(request,pk):
    course = get_object_or_404(Courses, pk=pk)
    return render(request, 'blog/course.html', context={'course':course})

blog/templates/blog/archives.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block meta %}
<title>文章归档-我的博客</title>
{% endblock %}

{% block article %}
<div class="post-block archive" style="opacity: 2; display: block;">
    {% regroup posts by created_time|date:"Y" as years %}
    {% for year in years %}
        <h4>{{ year.grouper }}年 ({{ year.list | length }})</h4>
        {% regroup year.list by created_time|date:"m" as months %}
        {% for month in months %}
            <h5>{{ month.grouper }}月</h5>
            <div class="list-group">
                <ul class="posts">
                {% for post in month.list %}
                    <li style="list-style-type:none">
                        <span>{{ post.created_time | date:"d" }}日</span>&nbsp;&nbsp;&nbsp;
                        <a href="{{ post.get_absolute_url }}">{{ post.title | slice:":50"}}</a>
                        <span style="float: right">{{ post.views }}&nbsp; views</span></span>
                    </li>
               {% endfor %}
               </ul>
          </div>
        {% endfor %}
        {% if forloop.last == False %}
          <hr>
        {% endif %}
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog/article.html
{% extends 'base.html' %}
{% load blog_tags %}
{% load staticfiles %}

{% block meta %}
<title>{{ post.title }}</title>
<meta name="description" content="{{ post.excerpt }}"/>
<meta name="keywords" content="{% for tag in post.tag.all %}{{ tag.name }},{% endfor %}"/>
{% endblock %}

{% block article %}
<div id="posts" class="posts-expand">
    <article class="post post-type-normal" itemscope="" itemtype="http://schema.org/Article">
        <div class="post-block article_post" style="opacity: 1; display: block;">
            <!--文章头部信息-->
            <header class="post-header" style="opacity: 1; display: block; transform: translateY(0px);">
                <!--文章标题-->
                <h2>{{ post.title }}</h2>

                <!--发布信息-->
                <div class="article-post-meta">
                    <!--发布时间-->
                    <span class="post-time">
                        <span itemprop="dateCreated datePublished" >日期：{{ post.created_time }}</span>
                    </span>

                    <!--文章分类-->
                    <span class="post-category">
                        <span itemprop="about" >分类：<a href="{% url 'blog:category' post.category.id %}" itemprop="url" rel="index"><span itemprop="name">{{ category.name }}</span></a></span>
                    </span>

                    <!--文章标签-->
                    <span class="post-tags">
                        <span class="busuanzi-value" id="busuanzi_value_page_pv">标签：
                            {% for tag in post.tag.all %}
                                <a href="{{ tag.get_absolute_url }}">{{ tag.name }}</a>
                            {% endfor %}
                        </span>
                    </span>

                    <!--阅读次数-->
                    <span class="post-views">
                        <span class="busuanzi-value" id="busuanzi_value_page_pv">阅读（{{ post.views }}）</span>
                    </span>

                    <!--评论次数-->
                    <span class="post-tags">
                        <span class="busuanzi-value" id="busuanzi_value_page_pv">
                            评论({% get_comment_count post %})
                        </span>
                    </span>


                </div>
            </header>

            <!--文章内容-->
            <div class="post-body" itemprop="articleBody" style="opacity: 1; display: block; transform: translateY(0px);">
                {% autoescape off %}
                    {{ post.body }}
                {% endautoescape %}
            </div>
            <!--版权声明-->
            <div>
                <br>
                <ul class="post-copyright">
                </ul>
            </div>

            <!--文章底部信息-->
            <footer class="post-footer">
                <div class="post-nav">
                    <div class="post-nav-next post-nav-item">
                        {% for relative_post in relative_posts %}
                            <li class="relative_posts"><a class="relative_posts" href="{{ relative_post.get_absolute_url }}" title="{{ relative_post.title }}"><i class="fa fa-minus" aria-hidden="true"></i>{{ relative_post }}</a></li>
                        {% endfor %}
                    </div>
                </div>
            </footer>

            <!--评论提交区域-->
            <div class="comment-area">
                <h3 class="comment-area-title">提交评论</h3>
                {% if user.is_authenticated  %}
                    <form id = "comment_form" action="{% url 'comment:update_comment' %}" method="POST">

                        <div id="reply_content_container" style="display:none;">
                            <p id="reply_title">回复：</p>
                            <div id="reply_content"></div>
                        </div>

                        {% csrf_token %}
                        {% get_comment_form post as comment_form%}

                        {% for field in comment_form %}
                            {{ field }}
                        {% endfor %}

                        <span id="comment_error" class="text-danger pull-left"></span>
                        <input class="btn btn-primary pull-right" type="submit" value="评论">
                    </form>
                {% else %}
                    请先登录后评论
                    <a class = "btn btn-primary" href="{% url 'blog:login' %}?from={{ request.get_full_path }}">登录</a>
                    <span> or </span>
                    <a class = "btn btn-danger" href="{% url 'blog:register' %}?from={{ request.get_full_path }}">注册</a>
                {% endif %}
            </div>

            <!--评论显示区域-->
            <div class="comment-area">
                <h3 class="comment-area-title" id="comment">评论列表</h3>
                <div id="comment_list">
                    {% get_comments_list post as comments %}
                    {% for comment in comments %}
                        <div id="root_{{ comment.pk }}" class="comment">
                            <div class="comment_user">
                                {% ifequal comment.user.username 'reborn' %}
                                    <img class="user_avatar" src="{% static 'blog/image/touxiang.jpg' %}" alt="{{ comment.user.username }}" style="border: 1px solid #ccc">
                                    <span class="user_name comment_name">
                                        <span style="color: #d23f31;">博主</span>
                                    </span>
                                {% else %}
                                    <img class="user_avatar" src="{% static 'blog/image/touxiang.png' %}" alt="{{ comment.user.username }}" style="border: 1px solid #ccc">
                                    <span class="user_name comment_name">
                                        <span >{{ comment.user.username }}</span>
                                    </span>
                                {% endifequal %}
                            </div>
                            <div class="comment_body">

                                <div class="comment_content" id="comment_{{ comment.pk }}">
                                    {{ comment.text|safe }}
                                </div>

                                <p class="comment_bottom">
                                    <span class="">{{ comment.comment_time|date:'Y-m-d H:i:s'}}</span>
                                    <span class="reply_button"><a class="" href="javascript:reply({{ comment.pk }})">回复</a></span>
                                </p>

                                {% if reply.user.username is  null %}
                                <ul class="comment_reply">
                                    {% for reply in comment.root_comment.all %}
                                        <li class="reply">
                                            {% ifequal reply.user.username 'reborn' %}
                                                <img class="reply_avatar" src="{% static 'blog/image/touxiang.jpg' %}" alt="{{ reply.user.username }}" style="border: 1px solid #ccc">
                                                <div class="reply_body">
                                                    <p>
                                                        <span class="comment_name reply_name" style="color: #d23f31;">博主</span>
                                            {% else %}
                                                <img class="reply_avatar" src="{% static 'blog/image/touxiang.png' %}" alt="{{ reply.user.username }}">
                                                <div class="reply_body">
                                                    <p>
                                                        <span class="comment_name reply_name">{{ reply.user.username }}</span>
                                            {% endifequal %}
                                                    <span><i class="fa fa-share" aria-hidden="true"></i></span>
                                            {% ifequal reply.reply_to.username 'reborn' %}
                                                    <span class="comment_name" style="color: #d23f31;">博主:</span>
                                            {% else %}
                                                    <span class="comment_name">{{ reply.reply_to.username }}:</span>
                                            {% endifequal %}
                                                    </p>
                                                <div class = "reply_content" id="comment_{{ reply.pk }}">
                                                    {{ reply.text|safe }}
                                                </div>
                                                 <p class="comment_bottom">
                                                    <span>{{ reply.comment_time|date:'Y-m-d H:i:s'}}</span>
                                                    <span><a href="javascript:reply({{ reply.pk }})">回复</a></span>
                                                </p>
                                            </div>
                                        </li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                            </div>
                        </div>
                     {% empty %}
                            此篇文章暂无评论，快来说两句吧！
                    {% endfor %}
                </div>
            </div>
        </div>
    </article>
</div>



{% endblock %}

{% block script_extends %}
    <script type="text/javascript">
            function reply(reply_comment_id){
            // 设置值
            $('#reply_comment_id').val(reply_comment_id);
            var html = $("#comment_" + reply_comment_id).html();
            $('#reply_content').html(html);
            $('#reply_content_container').show();
            $('html').animate({scrollTop: $('#comment_form').offset().top - 60}, 300, function(){
                CKEDITOR.instances['id_text'].focus();
            });
        }

        $("#comment_form").submit(function(){
            // 清空错误内容
            $("#comment_error").text('');
            // 更新数据
            if(CKEDITOR.instances['id_text'].document.getBody().getText().trim() === ''){
                // 显示错误信息
                $("#comment_error").text('评论内容不能为空');
                return false;
            }
        });

    </script>
{% endblock %}

{% block toc_sidebar %}
    <div class="siderbar" >
        <div class="widget git_tag">
            <div class="title">
                <h3>文章目录</h3>
            </div>
            <div class="post-toc" style="max-height: 448px;">
                {% autoescape off %}
                {{ post.toc }}
                {% endautoescape %}
            </div>
        </div>
    </div>
{% endblock %}
{##}
{#{% block tag_sidebar %}#}
{##}
{#    #}
{#{% endblock %}#}
{##}
{#{% block wechat_sidebar %}#}
{##}
{#{% endblock %}#}
{##}
{#{% block links %}#}
{##}
{#{% endblock %}#}

blog/templates/blog/category.html
{% extends 'base.html' %}

{% block meta %}
<title>当前分类：{{ cate_name }}-我的文章</title>
{% endblock %}